#ifndef __TARGET_MODE_H
#define __TARGET_MODE_H

#include "stm32f1xx_hal.h"

typedef enum
{
    TARGET_MODE_TOILET = 0,
    TARGET_MODE_EXIT,
    TARGET_MODE_OFFICE,
    TARGET_MODE_STAIRS,
    TARGET_MODE_ELEVATOR,
    TARGET_MODE_EXTINGUISHER,
    TARGET_MODE_NONE,
    TARGET_MODE_COUNT
} TargetMode_t;

#endif /* __TARGET_MODE_H */
